version: "3.9"
services:
  backup:
    image: minio/mc
    container_name: rgps-backup
    entrypoint: ["/bin/sh","-c","/scripts/pg_dump.sh && crond -f"]
    volumes:
      - ./backup/pg_dump.sh:/scripts/pg_dump.sh:ro
      - ./backup:/backup
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=db
      - PGDATABASE=${POSTGRES_DB}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MC_HOST_minio=http://minioadmin:minioadmin@rgps-minio:9000
    depends_on:
      - db
      - minio
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-05-10T02-44-02Z
    container_name: rgps-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - rgps_minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

volumes:
  rgps_minio_data:
