version: "3.9"

services:
  db:
    image: postgres:16
    container_name: rgps-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-rgps}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-rgps_pass}
      POSTGRES_DB: ${POSTGRES_DB:-rgps_backoffice}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: rgps-backend
    depends_on:
      - db
    environment:
      DB_DSN: "postgres://${POSTGRES_USER:-rgps}:${POSTGRES_PASSWORD:-rgps_pass}@db:5432/${POSTGRES_DB:-rgps_backoffice}?sslmode=disable"
      PORT: 8080
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: rgps-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development


volumes:
  db_data:

networks:
  default:
    name: rgps.backoffice.network
